on:
  push:
    branches: [master]

jobs:
  stage:
    if: github.event.pull_request.merged == 'true'
    name: 'Production release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.1

      - name: 'Build Docker image'
        run: |
          docker build . --tag eu.gcr.io/${{ secrets.PRODUCTION_PROJECT }}/${{ secrets.PRODUCTION_SERVICE }}:latest

      - name: 'Authenticate into Google Cloud Platform'
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: 'Push image to Google Cloud Container Registry'
        run: docker push eu.gcr.io/${{ secrets.PRODUCTION_PROJECT }}/${{ secrets.PRODUCTION_SERVICE }}

      - name: 'Install beta commands and deploy on cloud run'
        run: |
          gcloud components install beta --quiet
          gcloud beta run deploy ${{ secrets.PRODUCTION_SERVICE }} --quiet --image eu.gcr.io/${{ secrets.PRODUCTION_PROJECT }}/${{ secrets.PRODUCTION_SERVICE }} --project ${{ secrets.PRODUCTION_SERVICE }} --region europe-west1 --platform managed
