on:
  pull_request:
    types: [closed]
    branches:
      - master
      - stage

jobs:
  pull-request-closed:
    name: 'Pull request closed'
    runs-on: ubuntu-latest
    env:
      REGION: europe-west1
      PROJECT_NAME: trisbee-staging
      SERVICE_NAME: fe-cloud-run-example-pr-${{ github.event.number }}
      DOCKER_IMG: eu.gcr.io/trisbee-staging/fe-cloud-run-example:${{ github.event.number }}
    steps:
      - name: 'Google Cloud setup'
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '306.0.0'
          project_id: ${{ env.PROJECT_NAME }}
          service_account_key: ${{ secrets.FE_STAGE_GCP_SA_KEY }}
          export_default_credentials: true

      - name: 'Remove temporary service from Google Cloud'
        run:  |
          gcloud run services delete ${{ env.SERVICE_NAME }} \
            --project=${{ env.PROJECT_NAME }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --quiet \

      - name: 'Remove Docker image from Cloud'
        run: gcloud container images delete ${{ env.DOCKER_IMG }}

      - name: 'Send URL address to PR as comment'
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          append: true
          message: |
            Service URL ${{ env.SERVICE_URL }} deleted.
