on:
  pull_request:
    branches:
      - master
      - stage

jobs:
  stage:
    name: 'Pull request'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.1

      - name: 'Build Docker image'
        run: |
          docker build . --tag pr-{{ process.env.GITHUB_REPOSITORY_SLUG }}:{{ process.env.GITHUB_SHA }}
