on:
  push:
    branches: [stage]

jobs:
  stage:
    name: 'Stage release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Google Cloud setup'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.STAGE_PROJECT }}
          service_account_key: ${{ secrets.FE_STAGE_GCP_SA_KEY }}
          export_default_credentials: true

      - name: 'Google Cloud info'
        run: gcloud info

      - name: 'Build Docker image'
        run: gcloud builds submit --tag eu.gcr.io/${{ secrets.STAGE_PROJECT }}/${{ secrets.STAGE_SERVICE }}:latest

      - name: 'Authenticate into Google Cloud Platform'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: 'Push image to Google Cloud Container Registry'
        run: docker push eu.gcr.io/${{ secrets.STAGE_PROJECT }}/${{ secrets.STAGE_SERVICE }}

      - name: 'Install beta commands and deploy on cloud run'
        run: |
          gcloud components install beta --quiet
          gcloud beta run deploy ${{ secrets.STAGE_SERVICE }} --quiet --image eu.gcr.io/${{ secrets.STAGE_PROJECT }}/${{ secrets.STAGE_SERVICE }} --project ${{ secrets.STAGE_PROJECT }} --region europe-west1 --platform managed
