on:
  push:
    branches: [stage]

jobs:
  stage:
    name: 'Stage release'
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: trisbee-staging
      SERVICE_NAME: fe-cloud-run-example
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Google Cloud setup'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ env.PROJECT_NAME }}
          service_account_key: ${{ secrets.FE_STAGE_GCP_SA_KEY }}
          export_default_credentials: true

      - name: 'Google Cloud info'
        run: gcloud info

      - name: 'Build Docker image'
        run: gcloud builds submit --tag eu.gcr.io/${{ env.PROJECT_NAME }}/${{ env.SERVICE_NAME }}:latest

      - name: 'Install beta commands and deploy on cloud run'
        run: |
          gcloud components install beta --quiet
          gcloud beta run deploy ${{ env.SERVICE_NAME }} --quiet --image eu.gcr.io/${{ env.PROJECT_NAME }}/${{ env.SERVICE_NAME }} --project ${{ env.PROJECT_NAME }} --region europe-west1 --platform managed
